version: '3'
  
services:
  mysql:
    image: old-product-mysql:v1
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: product_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
  product-api:
    image: old-product-api:v1
    depends_on:
      - mysql
    ports:
- "8081:80"
